import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  planning: [{type: 'autogenerated', dirName: 'planning'}],

  development: [{type: 'autogenerated', dirName: 'development'}],
  
  using_project: [{type: 'autogenerated', dirName: 'using_project'}],
  
  apoio: [{type: 'autogenerated', dirName: 'apoio'}],

  about_us: [{type: 'autogenerated', dirName: 'about_us'}],
};

export default sidebars;